### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by rpx99** [albertolerda/html-to-cl-who#1]
I want to suggest a bit more context / extended instructions:

Clone the repo into _~/common-lisp_

`git clone https://github.com/albertolerda/html-to-cl-who.git`

Start _sbcl_ and

`(ql:quickload '(:plump :command-line-arguments :hunchentoot :cl-who))`

Load the tool:

`(asdf:load-system :html-conv)`

Now you can open the Browser:

Browserlink: [http://localhost:3333/](http://localhost:3333/)

[Youtube Demovideo](https://www.youtube.com/watch?v=269tBEWzke4&list=PLFdMuo0ICT2C3gOqkDL83bpBhJtsF9e5r)

More info on asdf:
[ASDF Config](https://asdf.common-lisp.dev/asdf/Configuring-ASDF-to-find-your-systems.html)
[ASDF Loading](https://asdf.common-lisp.dev/asdf/Loading-a-system.html)

**Comment by albertolerda** [comment]
Thank you! Good idea, I'll update the README!
