### ISSUE TITLE
HTML comments aren't parsed

### ISSUE THREAD

**Issue by gitthail** [albertolerda/html-to-cl-who#5]
Comments like above don't parse, throw an error.

**Comment by albertolerda** [comment]
What do you think about https://github.com/albertolerda/html-to-cl-who/pull/6 ? The idea is to create a lisp comment and parse the text recursively

**Comment by gitthail** [comment]
I can't quite follow how that recursive call to build-sexp works (I'm too dumb) - but it does! I've merged your fix locally and haven't had an issue so far so will mark this as closed. Thank you
